export const DEFAULT_SPIN_THE_WHEEL_CONFIG = {
  id: 'demo-spin-the-wheel',
  title: 'Daily Voucher Spin',
  description: 'Spin the wheel to unlock limited time vouchers.',
  backgroundImage: require('../../../assets/prizewheel2.png'),
  pointerImage: require('../../../assets/spinIndicator.png'),
  ctaLabel: 'Spin & Win',
  spinDuration: 4500,
  rotationCount: 6,
  segments: [
    {
      id: 'voucher-coffee',
      label: 'Free Coffee',
      color: '#FF6B6B',
      textColor: '#FFFFFF',
      weight: 1,
      reward: {
        type: 'voucher',
        title: 'Free Coffee Voucher',
        description: 'Grab a complimentary coffee from any partner cafe.',
        icon: require('../../../assets/vouchersIcon3.png'),
      },
    },
    {
      id: 'voucher-lunch',
      label: 'Lunch Treat',
      color: '#FFD166',
      textColor: '#3C486B',
      weight: 1,
      reward: {
        type: 'voucher',
        title: 'Lunch Treat Voucher',
        description: '$10 off on your next lunch order.',
        icon: require('../../../assets/vouchersIcon3.png'),
      },
    },
    {
      id: 'voucher-surprise',
      label: 'Mystery Deal',
      color: '#4ECDC4',
      textColor: '#1A1A1A',
      weight: 0.75,
      reward: {
        type: 'voucher',
        title: 'Mystery Voucher',
        description: 'A surprise offer revealed when you win.',
        icon: require('../../../assets/vouchersIcon3.png'),
      },
    },
    {
      id: 'voucher-fashion',
      label: 'Style Boost',
      color: '#6C63FF',
      textColor: '#FFFFFF',
      weight: 1,
      reward: {
        type: 'voucher',
        title: 'Style Boost Voucher',
        description: '15% off apparel and accessories.',
        icon: require('../../../assets/vouchersIcon3.png'),
      },
    },
    {
      id: 'voucher-dessert',
      label: 'Dessert Dash',
      color: '#FF9F1C',
      textColor: '#1A1A1A',
      weight: 1.5,
      reward: {
        type: 'voucher',
        title: 'Dessert Dash Voucher',
        description: 'Claim a free dessert with any meal.',
        icon: require('../../../assets/vouchersIcon3.png'),
      },
    },
    {
      id: 'voucher-travel',
      label: 'Travel Perk',
      color: '#118AB2',
      textColor: '#FFFFFF',
      weight: 0.5,
      reward: {
        type: 'voucher',
        title: 'Travel Perk Voucher',
        description: 'Save $20 on your next booking.',
        icon: require('../../../assets/vouchersIcon3.png'),
      },
    },
  ],
  summary: {
    heading: 'Today\'s voucher highlights',
    items: [
      {
        id: 'voucher-coffee',
        title: 'Free Coffee',
        subtitle: 'Redeemable at partner cafes.',
      },
      {
        id: 'voucher-lunch',
        title: 'Lunch Treat',
        subtitle: '$10 off when you dine out.',
      },
      {
        id: 'voucher-dessert',
        title: 'Dessert Dash',
        subtitle: 'Complimentary dessert for dinner plans.',
      },
    ],
  },
};
